### ISSUE TITLE
Module Review

### ISSUE THREAD

**Issue by Pierre-Gilles** [vincentBesseau/gladys-netatmo#1]
Hello !

Je viens de regarder ton module Netatmo ! Top, joli boulot :)

Plusieurs remarques : 

- Plutôt que de demander de faire un script pour que ton module fonctionne, ce qui est un peu tech, j'aimerais au possible éviter de demander de faire des scripts pour tout (bon je suis d'accord c'est pas le cas partout dans Gladys mais j'aimerais virer ça à l'avenir), pourrait tu faire un setInterval avec un défaut à 30 minute et éventuellement proposer à l'utilisateur de créer un param (facultatif) pour spécifier son temps de rafraichissement ? ( tu peux t'en affranchir dans un premier temps, juste le default peut suffire)
- La façon dont les boxs sont créées va un peu changer ( ça sera plus simple ), je viens de bosser tout le week-end dessus. Il y a aura une modification à faire dessus assez vite, je détaillerais comment faire à la sortie de la nouvelle version en bêta.
- Les phrases que tu créé je ne suis pas contre en soit, mais j'ai l'impression qu'il s'agit de features plus "natives" que lié à ton module Netatmo. Je comprends que en ayant besoin tu les ai créée pour ton module, mais je ne sais pas vraiment si ça fait sens par rapport au projet qu'elles soient ici. Genre "Je serais absent aujourd'hui", c'est 100% lié à la gestion de la présence... Je serais pour les retirer du module et réfléchir de façon globale comment on gère ça dans Gladys :) Genre passer par des events natifs Gladys. A réfléchir. 

Voilà pour mon retour, dans tous les cas jolie boulot, il y a des supers possibilités avec ce module ! 

Ces remarques ne sont là que pour faire avancer le projet et que tout reste clean ;)

**Comment by vincentBesseau** [comment]
Salut Pierre-Gilles !

*  Concernant l'automatisation de la mise à jour du module, elle a été dev et sera présente lors de la prochaine release :).

*  J'attend avec impatience les informations sur la nouvelle méthode pour la création de box. J'ai vu que LepetitGeek allait faire un tutoriel bientôt

*  Je vais réfléchir sur comment intégrer dans Gladys.
Après il nous faudra tout de même un moyen d'actionner le mode absent au bout d'un certain temps défini par défaut ou défini par l'utilisateur .
Lorsque j'étais en vacances, grâce à Gladys et à telegram mon thermostat savait que je rentrais tel jour à telle heure :)

Merci pour avoir pris le temp de faire un retours !

**Comment by Pierre-Gilles** [comment]
> Concernant l'automatisation de la mise à jour du module, elle a été dev et sera présente lors de la prochaine release :).

Super ! 

> J'attend avec impatience les informations sur la nouvelle méthode pour la création de box. J'ai vu que LepetitGeek allait faire un tutoriel bientôt

Yes ! c'est work in progress de notre côté. On a repensé toute la création de boxs, c'est pas encore fini mais c'est en bonne voie. 

> Après il nous faudra tout de même un moyen d'actionner le mode absent au bout d'un certain temps défini par défaut ou défini par l'utilisateur .

Complètement d'accord avec toi :) Je vois tout à fait la feature, je pense juste que ça devrait être natif dans Gladys, histoire d'éviter que tous les modules réinvente la roue là dessus. J'ai créé une issue Github du coup sur le repo Gladys => https://github.com/GladysProject/Gladys/issues/297

**Comment by vincentBesseau** [comment]
Release 2 prenants en compte les remarques de cette issue : 
- Suppression de de box car pas encore developpable au sein d’un module.
- Mise à jour tout les x temps (défaut 30 minutes) du module.
- Changement automatique du thermostat en fonction du mode de la maison
(mode vacance de la maison : mode hors gel du thermostat, mode absent de la maison : mode absent du thermostat)
- Mise en place de sentence pour pouvoir modifier le mode du thermostat
